name: car_crud_dart
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.1

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  collection: ^1.16.0
  args: ^2.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
